### ISSUE TITLE
Sprint2: CommunitiesScreen/CommunityDetailScreen, Design and API

### ISSUE THREAD

**Issue by ezhao7** [GT-Hive/hive#12]
Hive Designs
Edge Case UI Designs (Edwin)
Add “Join/Create a community” UI design

Hive Application
Forgot Password - Email sent (Edwin)
Persisting data - redux persist for auth token (Roy)
Hive Login functionality (Roy)
Save auth token and renew every 12 hours before expire
TabNavigation at the Bottom (Roy)
Main Screen - Communities (Edwin/~~)
Make a listview UI
Get all Communities list from API
Search functionality
Click on Community -> navigate to Community Screen
Community Screen (Joshua)
Browse Community / Create Community (Joshua)

Hive API
Forgot password API
Add “content”, “image_url” columns in Community table
Restructure communities & interests tables
Remove relationship btw communities & interests
Define “user has many communities” just like interests

**Comment by sroyhong313** [comment]
I'll make a new Epic since this is old.
