### ISSUE TITLE
Add UI for interests at the end of registration

### ISSUE THREAD

**Issue by ezhao7** [GT-Hive/hive#3]
## Expected Behavior

After verifying their account, users should be able to then select a few groups from a list of communities that will prefill. 
## Current Behavior

Currently does not exist
## Possible Solution

Use flex box to display buttons. Current issue of needing buttons to be the same size of the text, rather than locking the same button size to varying text.
## Context

Without doing so, unable to proceed forward into the next screen to utilize the selected features.

**Comment by ezhao7** [comment]
Change colours when selected, not emoticons.

**Comment by sroyhong313** [comment]
Since we have the issue interest screen in zeplin, i'll close this issue.
