### ISSUE TITLE
Link up 'Open Mail App' button

### ISSUE THREAD

**Issue by ezhao7** [GT-Hive/hive#9]
## Possible Solution

`<Button onPress={() => Linking.openURL('mailto:support@hive.com') }
      title="support@example.com" />`

Check if this opens the mail app itself or if it opens a link on web browser.

**Comment by sroyhong313** [comment]
this will be handled on the API side. After user clicks 'Open Mail Button', the email address of user will be sent to the backend where emailing is handled there. What we need is a Toast that says something like 'Email Sent. Check your email.' 

I'll close this issue. Feel free to open it again if you think more discussion is needed. #1
